name: Bug Report
description: Report a bug
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: input
    id: kernel
    attributes:
      label: Kernel version
      placeholder: "Run: uname -r"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error messages
