name: Feature Request  
description: Request a new feature
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
